---
title: "Greenland - better of with or without Denmark"
authors: "Emil Uhre Sørensen, Rasmus Andsbjerg Johansen, Jonas Kolborg Nørgaard og Johanne Elkær Hansen"
output: html_document
date: "2025-05-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=6)
```

```{r libraries, include=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
```

## Load datasets
``` {r eval=TRUE}
GDP_per_Capita <- read_csv2("data/GDP per capita (current US$).csv")

Hisorical_Population <- read_csv2("data/Historical population.csv")

Life_expectancy <- read_csv("data/life-expectancy-at-birth-including-the-un-projections.csv")

GDP <- read_csv2("data/GDP.csv")

Net_migration <- read_csv2("data/Net migration.csv")

Child_mortality_under_5 <- read_csv("data/Transformed_Børnedødelighed (1).csv")
```

# GDP

```{r eval=TRUE}
# Convert from wide to long format
gdp_with_year <- GDP %>%
  pivot_longer(cols = -`Country Name`, names_to = "Year", values_to = "GDP") %>%
  mutate(Year = as.numeric(Year)) %>% 
  na.omit(GDP) %>%
  mutate(GDP = GDP / 1e9)

# Creating the ggplot
GDP_by_Country <- ggplot(gdp_with_year, aes(x = Year, y = GDP, color = `Country Name`)) +
  geom_line(size=1.5) +
  labs(title = "GDP Over Time by Country",
       x = "Year",
       y = "GDP (in billions)", 
       color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20), legend.title = element_text(size = 14),legend.text = element_text(size = 12))  

GDP_by_Country
```

```{r, eval=TRUE}
selected_countries <- c("Greenland", "Faroe Islands", "Iceland")

gdp_G_F_I <- gdp_with_year %>%
  filter(`Country Name` %in% selected_countries)


GDP_Greenland_FaroeIslands_Iceland <- ggplot(gdp_G_F_I, aes(x = Year, y = GDP, color = `Country Name`)) +
  geom_line(size=1.5) +
  labs(title = "GDP Greenland, Faroe Islands, and Iceland",
       x = "Year",
       y = "GDP (in billions)",
       color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20),legend.title = element_text(size = 14),legend.text = element_text(size = 12))

GDP_Greenland_FaroeIslands_Iceland
```
###Only Greenland
```{r eval=TRUE}
selected_countries_2 <- c("Greenland")

GDP_Greenland <- gdp_with_year %>%
  filter(`Country Name` %in% selected_countries_2)

# Creating the ggplot
GDP_Greenland <- ggplot(GDP_Greenland, aes(y=GDP, x=Year, color=`Country Name`)) +
  geom_line(size=1.5) +
  labs(title="GDP Greenland", x="Year", y="GDP (in billions)", color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20),legend.title = element_text(size = 14),legend.text = element_text(size = 12))+
  scale_color_manual(values = c("Greenland" = "springgreen3"))

GDP_Greenland
```

### Collecting the graphs
```{r, include=FALSE}
#install packages
#install.packages("patchwork")
#install.packages("scales")

#library
library(patchwork)
library(scales)
```

```{r, eval=TRUE}
# Using the patchwork package to arrange the plots
Collected_GDP<- GDP_by_Country | GDP_Greenland_FaroeIslands_Iceland / GDP_Greenland &
  scale_x_continuous(limits = c(1960, 2023))

Collected_GDP <- Collected_GDP + 
  plot_annotation(title = "GDP Over Time by Country")

Collected_GDP
```


```{r, include=FALSE}
#saving as jpeg-file

#jpeg("figures/Collected_GDP2.jpeg", width = 30, height = 16, units = "cm", res = 300)
#print(Collected_GDP)
#dev.off()
```


### Moveable graphs
Loading libraries for animation
```{r, include=FALSE}
#install.packages("plotly")
library(plotly)

#install.packages("gganimate")
library(gganimate)

##ianstll.packages("gifski")
library(gifski)
```

```{r eval=TRUE}
ggplotly(GDP_by_Country)
```


```{r eval=TRUE}
animated_plot <- GDP_by_Country +
  transition_reveal(Year) +
  labs(title = 'GDP Over Time by Country: 1960-2021')

GDP_animated <- animate(animated_plot, nframes = 100, fps = 10,
renderer = gifski_renderer())
#anim_save("GNP_2.gif", animation = GDP_animated)

GDP_animated
```

```{r eval=TRUE}
ggplotly(GDP_Greenland_FaroeIslands_Iceland)
```

```{r eval=TRUE}
animated_plot <- GDP_Greenland_FaroeIslands_Iceland +
  transition_reveal(Year) +
  labs(title = 'GDP Over Time by Country: 1960-2021')

GDP_animated_Greenland_FaroeIslands_Iceland <- animate(animated_plot, nframes = 100, fps = 10,
renderer = gifski_renderer())
#anim_save("GDP_animated_Greenland_FaroeIslands_Iceland_2.gif", animation = GDP_animated_Greenland_FaroeIslands_Iceland)

GDP_animated_Greenland_FaroeIslands_Iceland
```

#GDP per Capita
```{r eval=TRUE}
# Convert from wide to long format
GDP_Capita_year <- GDP_per_Capita %>%
  pivot_longer(cols = -`Country Name`, names_to = "Year", values_to = "GDP per Capita") %>%
  mutate(Year = as.numeric(Year)) %>% 
  na.omit(GDP)

# Creating the ggplot
GDP_Capita_year <- ggplot(GDP_Capita_year, aes(x = Year, y = `GDP per Capita`, color = `Country Name`)) +
  geom_line(size=1.5) +
  labs(title = "GDP per Capita Over Time by Country",
       x = "Year",
       y = "GDP per Capita (current US dollars)", 
       color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20), legend.title = element_text(size = 14),legend.text = element_text(size = 12))

GDP_Capita_year
```
```{r eval=TRUE}
ggplotly(GDP_Capita_year)
```

```{r, include=FALSE}
#saving as jpeg-file

#jpeg("figures/GDP_Capita_year.jpeg", width = 25, height = 16, units = "cm", res = 300)
#print(GDP_Capita_year)
#dev.off()
```


# Life Expectanty
```{r eval=TRUE}
head(Life_expectancy)
```

```{r eval=TRUE}
Life_expectancy_with_year <- Life_expectancy %>% 
  filter(Year <= "2023") %>%  
  mutate(Year = as.numeric(Year), `Life expectancy - Sex: all - Age: 0 - Variant: estimates` =as.numeric(`Life expectancy - Sex: all - Age: 0 - Variant: estimates`)) %>% 
  rename(Life_expectancy_data = `Life expectancy - Sex: all - Age: 0 - Variant: estimates`)

# Creating the ggplot
Life_expectancy_by_birth <- ggplot(Life_expectancy_with_year, aes(x=Year, y= Life_expectancy_data, color=Entity)) +
  geom_line(size=1.5) +
  labs(title="Life Expectancy at Birth", x="Year", y="Life Expectancy (in years)", color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20),legend.title = element_text(size = 14),legend.text = element_text(size = 12))

Life_expectancy_by_birth
```

```{r, include=FALSE}
#saving as jpeg-file

#jpeg("figures/Life_expectancy_by_birth.jpeg", width = 25, height = 16, units = "cm", res = 300)
#print(Life_expectancy_by_birth)
#dev.off()
```

### Moveable graphs
```{r eval=TRUE}
ggplotly(Life_expectancy_by_birth)
```

```{r eval=TRUE}
animated_plot_LE <- Life_expectancy_by_birth +
  transition_reveal(Year) +
  labs(title = 'Life expectancy at birth: 1950-2023')

Life_expectancy_by_birth_animated <- animate(animated_plot_LE, nframes = 100, fps = 10, renderer = gifski_renderer())
#anim_save("Life_expectancy_by_birth_animated_2.gif", animation = Life_expectancy_by_birth_animated)

Life_expectancy_by_birth_animated
```

# Child Mortality
```{r eval=TRUE}
Child_mortality <- Child_mortality_under_5 %>%
  pivot_longer(cols = -`Country Name`, names_to = "Year", values_to = "Child Mortality") %>%
  mutate(Year = as.numeric(Year)) %>% 
  na.omit(Child_mortality_under_5)

# Creating the ggplot
Child_mortality_5 <- ggplot(Child_mortality, aes(x=Child_mortality$Year, y= `Child Mortality`, color= `Country Name`)) +
  geom_line(size=1.5) +
  labs(title="Child mortality under 5", x="Year", y="Child mortality (per 1000)", color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20),legend.title = element_text(size = 14),legend.text = element_text(size = 12))


Child_mortality_5
```
```{r, include=FALSE}
#saving as jpeg-file

#jpeg("figures/Child_mortality_5.jpeg", width = 25, height = 16, units = "cm", res = 300)
#print(Child_mortality_5)
#dev.off()
```

### Moveable graphs
```{r eval=TRUE}
ggplotly(Child_mortality_5)
```


```{r eval=TRUE}
animated_plot_LE <- Child_mortality_5 +
  transition_reveal(Year) +
  labs(title = 'Child mortality under 5')

Child_mortality_under_5_animated <- animate(animated_plot_LE, nframes = 100, fps = 10, renderer = gifski_renderer())
#anim_save("Child_mortality_under_5_animated.gif", animation = Child_mortality_under_5_animated)

Child_mortality_under_5_animated
```


# Net Migration
```{r eval=TRUE}
Net_migratuion_with_year <- Net_migration %>%
  pivot_longer(cols = -`Country Name`, names_to = "Year", values_to = "Net migration") %>%
  mutate(Year = as.numeric(Year)) %>% 
  na.omit(Net_migration)

# Creating the ggplot
Net_migration_year <- ggplot(Net_migratuion_with_year, aes(y= `Net migration`, x= Year, color= `Country Name`)) +
  geom_line(size=1.5) +
  labs(title="Net Migration", x="Year", y="Net Migration", color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20),legend.title = element_text(size = 14),legend.text = element_text(size = 12))

Net_migration_year
```

### Only Greenland
```{r eval=TRUE}
selected_countries_2 <- c("Greenland")

Net_migration_Greenland <- Net_migratuion_with_year %>%
  filter(`Country Name` %in% selected_countries_2)

# Creating the ggplot
Net_migration_only_Greenland <- ggplot(Net_migration_Greenland, aes(y= `Net migration`, x= Year, color= `Country Name`)) +
  geom_line(size=1.5) +
  labs(title="Net Migration Greenland", x="Year", y="Net Migration", color = "Country") +
  theme_minimal()+
  theme(plot.title = element_text(size = 20),legend.title = element_text(size = 14),legend.text = element_text(size = 12))+
  scale_color_manual(values = c("Greenland" = "springgreen3"))


Net_migration_only_Greenland
```


###Collected Graph
```{r, eval=TRUE}
# Using the patchwork package to arrange the plots
Collected_Net_migration <- Net_migration_year | Net_migration_only_Greenland &
  scale_x_continuous(limits = c(1960, 2023))

Collected_Net_migration  <- Collected_Net_migration + 
  plot_annotation(title = "Net Migration")

Collected_Net_migration
```


```{r, include=FALSE}
#saving as jpeg-file

#jpeg("figures/Collected_Net_migration2.jpeg", width = 25, height = 16, units = "cm", res = 300)
#print(Collected_Net_migration)
#dev.off()
```

### Moveable graphs
```{r eval=TRUE}
ggplotly(Net_migration_year)
```

```{r eval=TRUE}
ggplotly(Net_migration_only_Greenland)
```


```{r eval=TRUE}
animated_plot_LE <- Net_migration_year +
  transition_reveal(Year) +
  labs(title = 'Net Migration')

Net_migration_animated <- animate(animated_plot_LE, nframes = 100, fps = 10, renderer = gifski_renderer())
#anim_save("Net_migration_animated.gif", animation = Net_migration_animated)

Net_migration_animated
```

```{r eval=TRUE}
animated_plot_LE <- Net_migration_only_Greenland +
  transition_reveal(Year) +
  labs(title = 'Net Migration Greenland')

Net_migration_Greenland_animated <- animate(animated_plot_LE, nframes = 100, fps = 10, renderer = gifski_renderer())
#anim_save("Net_migration_Greenland_animated.gif", animation = Net_migration_Greenland_animated)

Net_migration_Greenland_animated
```



